site_name: Named Hosting Wiki
repo_url: https://github.com/Derkades/namedhosting_wiki
repo_name: Named Hosting Wiki
edit_uri: edit/main/docs/
markdown_extensions:
  - tables
theme:
  name: material
  # logo: assets/logo.png
  # favicon: assets/logo.png
  palette:
    scheme: slate
    primary: teal
